# Generated by Django 3.2.3 on 2021-09-12 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EcommerceApp', '0004_category_category_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='product_name',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
